export CUDA_VISIBLE_DEVICES=0

model_name=tcf7

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 128 \
  --cycle 144 \
  --d_core 128 \
  --batch_size 16 \
  --lradj cosine \
  --train_epochs 50 \
  --freq t \
  --itr 1 \

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --n_vars 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_core 64 \
  --d_ff 128 \
  --cycle 144 \
  --batch_size 32 \
  --lradj cosine \
  --train_epochs 50 \
  --freq t \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --n_vars 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 128 \
  --d_core 64 \
  --cycle 144 \
  --batch_size 32 \
  --train_epochs 50 \
  --freq t \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --n_vars 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 128 \
  --d_core 64 \
  --batch_size 32 \
  --cycle 144 \
  --lradj cosine \
  --train_epochs 50 \
  --freq t \
  --itr 1